spring:
  application:
    name: jpb

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:jobportal}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJwtTokenGenerationAndValidationPurpose12345}
  expiration: ${JWT_EXPIRATION:86400000}
  issuer: ${JWT_ISSUER:job-portal-backend}

